# Install: Manage basic resource setup, such as packages or service users.

---

- name: "Setup | Install | Default | Remove unwanted packages (e.g., to prevent conflicts or resolve incompatibilities)"
  ansible.builtin.package:
    name: "{{ __reboot_linux_packages_removal }}"
    state: "absent"
  when:
    - __reboot_linux_packages_removal is defined
    - (__reboot_linux_packages_removal | length) > 0


- name: "Setup | Install | Default | Install or upgrade packages"
  ansible.builtin.package:
    name: "{{ __reboot_linux_packages_install }}"
    state: "{{ 'latest' if reboot_linux_autoupgrade else 'present' }}"
  when:
    - __reboot_linux_packages_install is defined
    - (__reboot_linux_packages_install | length) > 0


- name: "Setup | Install | Default | Remove unwanted files and directories (e.g., to prevent conflicts or resolve incompatibilities)"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  when:
    - __reboot_linux_paths_removal is defined
    - (__reboot_linux_paths_removal | length) > 0
  loop: "{{ __reboot_linux_paths_removal }}"
