# Default variables and values for this role.
#
# These variables are designed to be easily overridden (as they have a low
# precedence) and typically allow users to customize the role's behavior.
# Each variable should have a clear comment above it, describing its purpose
# and how it fits into the role's functionality.

---

# String. Determines whether the managed resources should be "present" or
# "absent". Defaults to "present". Possible values:
#
# - "present": Ensures that required components, such as software packages,
#   are installed and configured.
# - "absent": Reverts changes as much as possible, such as removing packages,
#   deleting created users, stopping services, restoring modified settings, â€¦
sysctl_linux_state: "present"


# Boolean. If set to true, all managed packages will be upgraded during each
# Ansible run (e.g., when the package provider detects a newer version than
# the currently installed one). Defaults to false.
sysctl_linux_autoupgrade: false

sysctl_linux_profile: ""

sysctl_linux_parameters: {}

sysctl_linux_reload: true

sysctl_linux_verify: true

sysctl_linux_ignore_unknown_key_errors: false

sysctl_linux_config_dropin_file_name: "90-managed.conf"
