# Main entry point for the role.

---

- name: "Main | Include role initialization tasks"
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/init.yml"
    apply:
      tags:
        - "always"
        - "sysctl_linux_always"
  tags:
    - "always"
    - "sysctl_linux_always"


- name: "Main | Include setup tasks (install): best platform matches (if any), then default"
  ansible.builtin.include_tasks:
    file: "{{ __sysctl_linux_task_file }}"
    apply:
      tags:
        - "sysctl_linux_setup"
  vars:
    __sysctl_linux_task_file: "{{ role_path }}/tasks/setup/install/{{ __sysctl_linux_loop_item }}"
  when:
    - sysctl_linux_state == 'present'
    - __sysctl_linux_task_file is ansible.builtin.file
  loop: "{{ __sysctl_linux_platform_filenames_most_specific_first + ['default.yml'] }}"
  loop_control:
    loop_var: "__sysctl_linux_loop_item"
  tags:
    - "sysctl_linux_setup"


- name: "Main | Include configuration tasks: best platform matches (if any), then default"
  ansible.builtin.include_tasks:
    file: "{{ __sysctl_linux_task_file }}"
    apply:
      tags:
        - "sysctl_linux_config"
  vars:
    __sysctl_linux_task_file: "{{ role_path }}/tasks/config/{{ __sysctl_linux_loop_item }}"
  when:
    - sysctl_linux_state == 'present'
    - __sysctl_linux_task_file is ansible.builtin.file
  loop: "{{ __sysctl_linux_platform_filenames_most_specific_first + ['default.yml'] }}"
  loop_control:
    loop_var: "__sysctl_linux_loop_item"
  tags:
    - "sysctl_linux_config"


- name: "Main | Include setup tasks (uninstall): best platform matches (if any), then default"
  ansible.builtin.include_tasks:
    file: "{{ __sysctl_linux_task_file }}"
    apply:
      tags:
        - "sysctl_linux_setup"
  vars:
    __sysctl_linux_task_file: "{{ role_path }}/tasks/setup/uninstall/{{ __sysctl_linux_loop_item }}"
  when:
    - sysctl_linux_state == 'absent'
    - __sysctl_linux_task_file is ansible.builtin.file
  loop: "{{ __sysctl_linux_platform_filenames_most_specific_first + ['default.yml'] }}"
  loop_control:
    loop_var: "__sysctl_linux_loop_item"
  tags:
    - "sysctl_linux_setup"
