# Default variables and values for this role.
#
# These variables are designed to be easily overridden (as they have a low
# precedence) and typically allow users to customize the role's behavior.
# Each variable should have a clear comment above it, describing its purpose
# and how it fits into the role's functionality.

---

# String. Determines whether the managed resources should be "present" or
# "absent". Defaults to "present". Possible values:
#
# - "present": Ensures that required components, such as software packages,
#   are installed and configured.
# - "absent": Reverts changes as much as possible, such as removing packages,
#   deleting created users, stopping services, restoring modified settings, â€¦
reboot_linux_state: "present"


# Boolean. If set to true, all managed packages will be upgraded during each
# Ansible run (e.g., when the package provider detects a newer version than
# the currently installed one). Defaults to false.
reboot_linux_autoupgrade: false


reboot_linux_boot_time_cmd: "cat '/proc/sys/kernel/random/boot_id'"


reboot_linux_connect_timeout: -1


reboot_linux_msg: "Reboot initiated by Ansible (foundata.linux.reboot)"


reboot_linux_post_delay: 0


reboot_linux_timeout: 300


reboot_linux_test_cmd: "id"
